import { Abschnitt, Code, Hinweis, Liste, Merke, P } from '../../components/Ui'
import { Verweis } from '../../components/Verweis'
import { CodeBlock } from '../../lernen/CodeBlock'
import { Quiz } from '../../lernen/Quiz'
import { TryIt } from '../../lernen/TryIt'
import { beispiele, codeBloecke } from './Vererbung.code'

/**
 * CHAPTER 6.7 (English) - Inheritance & Interfaces
 */
export function Vererbung() {
  return (
    <>
      <Abschnitt titel="At a glance">
        <P>
          With <Code>extends</Code> a class takes over everything from another one - and may do
          single methods differently.
        </P>
        <TryIt modus="java" id="java-vererbung-einstieg" {...beispiele['java-vererbung-einstieg']} />
      </Abschnitt>

      <Abschnitt titel="“is a”">
        <CodeBlock code={codeBloecke.istEin} />
        <P>
          The subclass receives all fields and methods of the superclass. <Code>super(…)</Code> calls
          its constructor - and must come first in your own constructor, because without a finished
          superclass there is no valid object.
        </P>
      </Abschnitt>

      <Abschnitt titel="Polymorphism: the trick behind it">
        <P>
          This is the real payoff. The variable says <em>what you may expect</em>; the object decides{' '}
          <em>what happens</em>. So you can walk a list of <Code>Animal</Code> without knowing which
          species is next.
        </P>
        <TryIt modus="java" id="java-vererbung-polymorphie" {...beispiele['java-vererbung-polymorphie']} />
        <Hinweis variante="info">
          <Code>@Override</Code> replaces the inherited method. With <Code>super.method()</Code> you
          can still call the old version and only add something - that is what{' '}
          <Code>Cat.describe()</Code> does.
        </Hinweis>
        <P>
          <Code>instanceof</Code> checks the real type. Since Java 16 you may declare a variable
          right there: <Code>if (x instanceof Cat cat)</Code> saves the cast.
        </P>
      </Abschnitt>

      <Abschnitt titel="abstract: a blueprint with gaps">
        <P>
          An <Code>abstract</Code> class cannot be instantiated - it is only the shared foundation.
          An <Code>abstract</Code> method has no body: every subclass <em>must</em> provide one,
          otherwise it does not compile.
        </P>
        <TryIt modus="java" id="java-vererbung-abstract" {...beispiele['java-vererbung-abstract']} />
      </Abschnitt>

      <Abschnitt titel="Interfaces: abilities instead of ancestry">
        <P>
          An interface is a pure contract: “whoever implements this can do the following.” A class
          has exactly one superclass but may implement any number of interfaces.
        </P>
        <CodeBlock code={codeBloecke.wahl} />
        <TryIt modus="java" id="java-vererbung-interface" {...beispiele['java-vererbung-interface']} />
        <Hinweis variante="tipp">
          Rule of thumb: <strong>abstract class</strong> when there is shared data and code (“is a”).{' '}
          <strong>interface</strong> when it is only about an ability (“can”) - especially when it
          shows up in completely different classes.
        </Hinweis>
      </Abschnitt>

      <Abschnitt titel="enum and record">
        <P>
          Two special forms that save a lot of typing. An <Code>enum</Code> is a class with a fixed,
          countable set of objects - Java’s answer to the union type in TypeScript (
          <Verweis nr="4.8" />).
        </P>
        <TryIt modus="java" id="java-vererbung-enum" {...beispiele['java-vererbung-enum']} />
        <P>
          A <Code>record</Code> (since Java 16) is a class for pure data. Fields, constructor,
          getters, <Code>toString</Code> and <Code>equals</Code> are generated by the compiler - you
          write one line.
        </P>
        <TryIt modus="java" id="java-vererbung-record" {...beispiele['java-vererbung-record']} />
      </Abschnitt>

      <Abschnitt titel="And why does React do it differently?">
        <P>
          React has no inheritance between components. Instead of extending a base component, you nest
          small components - that is <strong>composition</strong> (<Verweis nr="4.3" />).
        </P>
        <CodeBlock code={codeBloecke.reactVergleich} />
        <P>
          Both solve the same problem: share code without copying it. Inheritance ties you to a
          hierarchy, composition stays flexible. Which is why the modern advice in Java is the same:{' '}
          <em>“composition over inheritance”</em> - inheritance yes, but in moderation.
        </P>
      </Abschnitt>

      <Abschnitt titel="Exercise">
        <TryIt
          modus="java"
          id="java-vererbung-uebung"
          {...beispiele['java-vererbung-uebung']}
          aufgabe={
            <>
              <p>Build a small payroll:</p>
              <Liste>
                <li>
                  <Code>abstract class Employee</Code> with <Code>name</Code>, a constructor,{' '}
                  <Code>getName()</Code>, the abstract method <Code>monthlySalary()</Code> and{' '}
                  <Code>describe()</Code> returning <Code>"Name: salary"</Code>
                </li>
                <li>
                  <Code>Developer(name, hours, hourlyRate)</Code> - salary ={' '}
                  <Code>hours * hourlyRate</Code>
                </li>
                <li>
                  <Code>Manager(name, fixedSalary)</Code> - salary = the fixed salary
                </li>
              </Liste>
              <p className="mt-1">
                <Code>describe()</Code> may appear <strong>only once</strong> - in{' '}
                <Code>Employee</Code>.
              </p>
            </>
          }
        />
      </Abschnitt>

      <Quiz
        fragen={[
          {
            frage: 'What does polymorphism do for Animal a = new Dog("Rex"); a.sound(); ?',
            antworten: [
              'The method of Animal runs.',
              'The method of Dog runs.',
              'It is a compile error.',
              'It depends on the order of the classes.',
            ],
            richtig: 1,
            erklaerung: 'The variable type decides what you MAY call. Which version runs is decided by the object.',
          },
          {
            frage: 'How many interfaces may a class implement?',
            antworten: ['none', 'exactly one', 'any number', 'at most two'],
            richtig: 2,
            erklaerung: 'Any number of interfaces - but only one superclass. That is exactly what interfaces are for.',
          },
          {
            frage: 'What is true for an abstract method?',
            antworten: [
              'It has a body that can be overridden.',
              'It has no body, and every concrete subclass must supply one.',
              'It is automatically static.',
              'It may only appear in interfaces.',
            ],
            richtig: 1,
            erklaerung: 'It is a promise without an implementation - which is why the class cannot be instantiated either.',
          },
        ]}
      />

      <Merke
        punkte={[
          <>
            <Code>extends</Code> means “is a” - one superclass, any number of interfaces.
          </>,
          <>
            <Code>super(…)</Code> calls the superclass constructor, <Code>super.m()</Code> its
            method.
          </>,
          'Polymorphism: the variable decides what is allowed - the object decides what happens.',
          <>
            <Code>abstract</Code> = shared code with gaps, <Code>interface</Code> = pure contract
            (with optional <Code>default</Code> methods).
          </>,
          <>
            <Code>enum</Code> for fixed sets, <Code>record</Code> for pure data classes.
          </>,
        ]}
      />
    </>
  )
}
